### ISSUE TITLE
[Parser] implement it

### ISSUE THREAD

**Issue by vendethiel** [faux-combinator/python#1]

**Comment by vendethiel** [comment]
@rightfold as you're the only pythonista I know -- which way is the most "pythonic"? Passing lambdas, or sub names that the lib calls dynamically?

**Comment by no-longer-on-githu-b** [comment]
Passing names is unnecessary indirection unless necessary, so prefer passing callables.

**Comment by no-longer-on-githu-b** [comment]
also don't call me a pythonista :( python sucks nutsack

**Comment by vendethiel** [comment]
Sure, but you **know** python, hence.

Isn't passing callables a PITA in python due to size limitations?

**Comment by no-longer-on-githu-b** [comment]
What size limitations?

**Comment by vendethiel** [comment]
I read (once) you were limited in the number of expressions you could put there, etc. String-calling, as indirect as it might be, allows for neat subclassing...

**Comment by no-longer-on-githu-b** [comment]
You can have up to 254 parameters in a function or lambda definition. Other than that, I have no idea what you're talking about. You can't call strings in Python.

**Comment by no-longer-on-githu-b** [comment]
It is true that a lambda can have only one expression as its body, but you can always use a local function and pass that. Passing function names or strings of Python code is just dumb.

**Comment by vendethiel** [comment]
Yeah, the one expression thing was what I was talking about. Guess I'll implement that then :-).

**Comment by no-longer-on-githu-b** [comment]
```
def g():
    pass
f(g)
```

this works fine

you don't need lambdas

**Comment by vendethiel** [comment]
I forgot I implemented it last year.

861efcd33d3956d0dc90a096f83fedfd19409b55
